### ISSUE TITLE
 TypeError: summary() missing 1 required positional argument: 'input_size'

### ISSUE THREAD

**Issue by yigong-tang** [savinay95n/PatchRefineNet#1]
i download the code, the weights and the data, but can not run. 

the info is:
`n>      python src/kvasir/refine-models/predict.py --base_model resunetplusplus --aux_model p64 --checkpoint True
=================================================================
Traceback (most recent call last):
  File "C:\Users\tang-yigong\Documents\Python-code\segment\PatchRefineNet-main\src\kvasir\refine-models\predict.py", line 80, in <module>
    summary(model)
TypeError: summary() missing 1 required positional argument: 'input_size'`

**Comment by savinay95n** [comment]
You can comment that line and retry. It was just for sanity check.
