### ISSUE TITLE
About the production of test sets and other files

### ISSUE THREAD

**Issue by sanlvbi123** [savinay95n/PatchRefineNet#2]
Hello author, I don’t know how to generate the test.npy, test_orig_gt.npy, test_gt.npy and other npy files in your project. Please give me some advice, because I want to change to other polyp segmentation data sets for experiments. I don’t know these now. How do you generate this thing? Thank you.

**Comment by savinay95n** [comment]
Check out generate_aux_training_data.py in src folder.
